# Data Preprocessing for UK Housing Price Analysis

This notebook performs initial data preprocessing on the raw UK housing dataset.

**Tasks performed:**
- Add unique `House_Id`
- Calculate `House_Age` (based on year 2025)
- Calculate `Price_Per_Sqft`
- Reorder columns for better readability
- Save the processed dataset to `data/processed/`

**Output file:** `house_price_reg_processed.csv`

In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

# Set display options
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
# Define project paths (relative to this notebook)
raw_data_path = Path('../../data/raw/house_price_regression_dataset.csv')
processed_data_path = Path('../../data/processed/house_price_reg_processed.csv')

# Create directories if they don't exist
processed_data_path.parent.mkdir(parents=True, exist_ok=True)

print(f"Raw data path: {raw_data_path}")
print(f"Processed data will be saved to: {processed_data_path}")

Raw data path: ..\..\data\raw\house_price_regression_dataset.csv
Processed data will be saved to: ..\..\data\processed\house_price_reg_processed.csv

In [4]:
# Load the raw dataset
df = pd.read_csv(raw_data_path)

print(f"Raw dataset loaded successfully!")
print(f"Shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print("\nFirst 5 rows:")
display(df.head())

Raw dataset loaded successfully!
Shape: 1,000 rows × 8 columns

First 5 rows:

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.60,0,5,262382.85
1,4272,3,3,2016,4.75,1,6,985260.85
2,3592,1,2,2016,3.63,0,9,777977.39
3,966,1,2,1977,2.73,1,8,229698.92
4,4926,2,1,1993,4.70,0,8,1041740.86

In [5]:
# Make a copy to avoid modifying original data
df_processed = df.copy()

# 1. Add House_Id as unique identifier
df_processed['House_Id'] = range(1, len(df_processed) + 1)

# 2. Calculate House_Age (based on 2025)
df_processed['House_Age'] = (2025 - df_processed['Year_Built']).astype(int)

# 3. Calculate Price_Per_Sqft
df_processed['Price_Per_Sqft'] = (df_processed['House_Price'] / df_processed['Square_Footage']).round(2)

print("Feature engineering completed:")
print(f"   - Added House_Id")
print(f"   - Added House_Age (reference year: 2025)")
print(f"   - Added Price_Per_Sqft")

Feature engineering completed:
   - Added House_Id
   - Added House_Age (reference year: 2025)
   - Added Price_Per_Sqft

In [6]:
# Define desired column order
desired_column_order = [
    'House_Id', 
    'Year_Built', 
    'House_Age',
    'House_Price', 
    'Price_Per_Sqft',
    'Square_Footage', 
    'Num_Bedrooms', 
    'Num_Bathrooms',
    'Lot_Size', 
    'Garage_Size', 
    'Neighborhood_Quality'
]

# Reorder columns
df_processed = df_processed[desired_column_order]

print("Columns reordered successfully.")
print("\nFinal column order:")
print(df_processed.columns.tolist())

Columns reordered successfully.

Final column order:
['House_Id', 'Year_Built', 'House_Age', 'House_Price', 'Price_Per_Sqft', 'Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Lot_Size', 'Garage_Size', 'Neighborhood_Quality']

In [7]:
print("=== Final Dataset Overview ===")
print(f"Total observations: {len(df_processed):,}")
print(f"Total features: {df_processed.shape[1]}")

print("\nData types:")
print(df_processed.dtypes)

print("\nMissing values:")
print(df_processed.isnull().sum())

print("\nSummary statistics:")
display(df_processed.describe().round(2))

print("\nFirst 5 rows of processed data:")
display(df_processed.head())

=== Final Dataset Overview ===
Total observations: 1,000
Total features: 11

Data types:
House_Id                  int64
Year_Built                int64
House_Age                 int32
House_Price             float64
Price_Per_Sqft          float64
Square_Footage            int64
Num_Bedrooms              int64
Num_Bathrooms             int64
Lot_Size                float64
Garage_Size               int64
Neighborhood_Quality      int64
dtype: object

Missing values:
House_Id                0
Year_Built              0
House_Age               0
House_Price             0
Price_Per_Sqft          0
Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
dtype: int64

Summary statistics:

,House_Id,Year_Built,House_Age,House_Price,Price_Per_Sqft,Square_Footage,Num_Bedrooms,Num_Bathrooms,Lot_Size,Garage_Size,Neighborhood_Quality
count,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00,1000.00
mean,500.50,1986.55,38.45,618861.02,226.92,2815.42,2.99,1.97,2.78,1.02,5.62
std,288.82,20.63,20.63,253568.06,26.93,1255.51,1.43,0.82,1.30,0.81,2.89
min,1.00,1950.00,3.00,111626.85,176.01,503.00,1.00,1.00,0.51,0.00,1.00
25%,250.75,1969.00,20.75,401648.23,211.45,1749.50,2.00,1.00,1.67,0.00,3.00
50%,500.50,1986.00,39.00,628267.29,219.60,2862.50,3.00,2.00,2.81,1.00,6.00
75%,750.25,2004.25,56.00,827141.28,234.18,3849.50,4.00,3.00,3.92,2.00,8.00
max,1000.00,2022.00,75.00,1108236.84,430.61,4999.00,5.00,3.00,4.99,2.00,10.00

First 5 rows of processed data:

,House_Id,Year_Built,House_Age,House_Price,Price_Per_Sqft,Square_Footage,Num_Bedrooms,Num_Bathrooms,Lot_Size,Garage_Size,Neighborhood_Quality
0,1,1981,44,262382.85,192.93,1360,2,1,0.60,0,5
1,2,2016,9,985260.85,230.63,4272,3,3,4.75,1,6
2,3,2016,9,777977.39,216.59,3592,1,2,3.63,0,9
3,4,1977,48,229698.92,237.78,966,1,2,2.73,1,8
4,5,1993,32,1041740.86,211.48,4926,2,1,4.70,0,8

In [8]:
# Save to processed folder
df_processed.to_csv(processed_data_path, index=False)

print(f"Processed dataset successfully saved to:")
print(f"   {processed_data_path}")
print(f"   Shape: {df_processed.shape[0]:,} rows × {df_processed.shape[1]} columns")

Processed dataset successfully saved to:
   ..\..\data\processed\house_price_reg_processed.csv
   Shape: 1,000 rows × 11 columns

In [9]:
# Quick verification
df_check = pd.read_csv(processed_data_path)
print("Verification successful! First 5 rows of saved file:")
display(df_check.head())

Verification successful! First 5 rows of saved file:

,House_Id,Year_Built,House_Age,House_Price,Price_Per_Sqft,Square_Footage,Num_Bedrooms,Num_Bathrooms,Lot_Size,Garage_Size,Neighborhood_Quality
0,1,1981,44,262382.85,192.93,1360,2,1,0.60,0,5
1,2,2016,9,985260.85,230.63,4272,3,3,4.75,1,6
2,3,2016,9,777977.39,216.59,3592,1,2,3.63,0,9
3,4,1977,48,229698.92,237.78,966,1,2,2.73,1,8
4,5,1993,32,1041740.86,211.48,4926,2,1,4.70,0,8